---
title: "Line layer"
---

> Layers are declared with the `DRAW` clause. Read the documentation for this clause for a thorough description of how to use it.

The line layer is used to create lineplots. Lineplots always connects records along the x-axis, in contrast to path layers which use the order of data to connect records. Lines are divided due to their grouping, which is the combination of the discrete mapped aesthetics and the columns specified in the layers `PARTITION BY`.

## Aesthetics
The following aesthetics are recognised by the point layer.

### Required
* `x`: Position along the x-axis
* `y`: Position along the y-axis

### Optional
* `size`: The size of each point
* `colour`: The default colour of the each point
* `stroke`: The colour of the stroke around each point (if any). Overrides `colour`
* `opacity`: The opacity of the point
* `linewidth`: The width of the line
* `linetype`: The type of line, i.e. the dashing pattern

## Settings
The line layer has no additional settings

## Data transformation
The line layer does not transform its data but passes it through unchanged

## Examples

TBD
